// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP_FjQguJER7uj7bpu_Qrjd6iErixTVC8',
    appId: '1:662221111815:web:e3555dc36c0adb557ce0a2',
    messagingSenderId: '662221111815',
    projectId: 'user-maneger',
    authDomain: 'user-maneger.firebaseapp.com',
    storageBucket: 'user-maneger.firebasestorage.app',
    measurementId: 'G-G9F787CVYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPNdEeGdhWU0sVYE4yogBx2SfBkWSYgpM',
    appId: '1:662221111815:android:1e1d3a2b7ab8b61b7ce0a2',
    messagingSenderId: '662221111815',
    projectId: 'user-maneger',
    storageBucket: 'user-maneger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwBSBnTeOZy2vTHYgqxU4M15hwcq9GnAM',
    appId: '1:662221111815:ios:fe305abf4d8cdbf27ce0a2',
    messagingSenderId: '662221111815',
    projectId: 'user-maneger',
    storageBucket: 'user-maneger.firebasestorage.app',
    androidClientId: '662221111815-nduu3kcfevkot050bmmop2jfg4646a3i.apps.googleusercontent.com',
    iosClientId: '662221111815-381bnt611p5gqm3t2vcif5fj1sbfe9bg.apps.googleusercontent.com',
    iosBundleId: 'com.example.userManeger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwBSBnTeOZy2vTHYgqxU4M15hwcq9GnAM',
    appId: '1:662221111815:ios:fe305abf4d8cdbf27ce0a2',
    messagingSenderId: '662221111815',
    projectId: 'user-maneger',
    storageBucket: 'user-maneger.firebasestorage.app',
    androidClientId: '662221111815-nduu3kcfevkot050bmmop2jfg4646a3i.apps.googleusercontent.com',
    iosClientId: '662221111815-381bnt611p5gqm3t2vcif5fj1sbfe9bg.apps.googleusercontent.com',
    iosBundleId: 'com.example.userManeger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP_FjQguJER7uj7bpu_Qrjd6iErixTVC8',
    appId: '1:662221111815:web:edc0733216fa77da7ce0a2',
    messagingSenderId: '662221111815',
    projectId: 'user-maneger',
    authDomain: 'user-maneger.firebaseapp.com',
    storageBucket: 'user-maneger.firebasestorage.app',
    measurementId: 'G-3HWPM6B2BN',
  );

}